
kind: pipeline
name: default

steps:
- name: build
  image: node
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
  - yarn
  - git config --global user.email "609448234@qq.com"
  - git config --global user.name "cacivy"
  - sed -i'' "s~//github.com/Cacivy/cacivy.github.io.git~//${GH_TOKEN}:x-oauth-basic@github.com/Cacivy/cacivy.github.io.git~" _config.yml
  - hexo g
  - hexo d

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
  - tag