language: node_js
node_js:
  - "node"
  - "7"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - hexo g
  - hexo d --config repository=https://${GH_TOKEN}@github.com/Cacivy/cacivy.github.io.git
