menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/Cacivy
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: http-blog-cacivy-com
duoshuo:

# Analytics
# google-analytics:
ga: UA-85349261-2

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
